############
#
# Copyright (c) 2024 Maxim Yudayev and KU Leuven eMedia Lab
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# Created 2024-2025 for the KU Leuven AidWear, AidFOG, and RevalExo projects
# by Maxim Yudayev [https://yudayev.com].
#
# ############

project       : "AidFOG"
trial_type    : "test" # recommend "test" for testing and "real" data
subject_id    : 0 # UID of the subject
trial_id      : 0 # UID of the trial
duration_s    : null

print_status  : True
print_debug   : True


host_ip : "192.168.69.103"
remote_broker_ips: []

is_remote_kill: True
remote_kill_ip: "192.168.69.100" # IP of Broker that delegates the primary kill signal (i.e CLI or GUI)

is_expose_to_remote_sub: True # If current Broker produces data that other Brokers can listen to


logging_spec:
  # Choose whether to periodically write data to files.
  stream_hdf5     : True # recommended over CSV since it creates a single file
  stream_csv      : False # will create a CSV per stream
  stream_video    : True
  stream_audio    : False
  stream_period_s : 10 # how often to save streamed data to disk
  clear_logged_data_from_memory: True # NOTE: IGNORED if dumping is also enabled below
  
  # Choose whether to write all data at the end.
  #   Seems to be mutually exclusive with `stream_` options.
  dump_csv        : False
  dump_hdf5       : False
  dump_video      : False
  dump_audio      : False
  
  # Additional configuration.
  #   Choose whether to save media separately or as part of HDF5/CSV files.
  videos_format   : "avi" # mp4 occasionally gets openCV errors about a tag not being supported?
  videos_in_hdf5  : False
  videos_in_csv   : False
  videos_is_use_intel_api : False
  audio_format    : "wav" # currently only supports WAV
  audio_in_hdf5   : False
  audio_in_csv    : False


producer_specs:
  # Stream from the DOTs lower limb tracking.
  - class: "DotsStreamer"
    device_mapping: 
      knee_right      : "40195BFC800B01F2"
      foot_right      : "40195BFC800B003B"
      pelvis          : "40195BFD80C20052"
      knee_left       : "40195BFC800B017A"
      foot_left       : "40195BFD80C200D1"
    master_device     : "pelvis" # wireless dot relaying messages, must match a key in the `device_mapping`
    num_joints        : 5
    sampling_rate_hz  : 60
    is_get_orientation: False
    is_sync_devices   : True
  
  # Stream from the Pupil Labs eye tracker, including gaze and video data.
  - class: "EyeStreamer"
    pupil_capture_ip      : "localhost"
    pupil_capture_port    : "50020"
    video_image_format    : "bgr"
    gaze_estimate_stale_s : 0.2
    stream_video_world    : True # the world video
    stream_video_eye      : False # video of the eye
    is_binocular          : True # uses both eyes for gaze data and for video
    shape_video_world: 
      - 720
      - 1280
      - 3
    shape_video_eye0: 
      - 192
      - 192
      - 3
    shape_video_eye1: 
      - 192
      - 192
      - 3
    fps_video_world       : 30.0
    fps_video_eye0        : 120.0
    fps_video_eye1        : 120.0

  # # Moticon insole pressure.
  # - class: "InsoleStreamer"
  #   sampling_rate_hz: 100


consumer_specs: []


pipeline_specs: []
