project       : "RevalExo"
trial_type    : "test" # recommend "test" for testing and "real" data
subject_id    : 0 # UID of the subject
trial_id      : 0 # UID of the trial
duration_s    : null

host_ip       : "10.244.21.115"
remote_broker_ips: []
remote_publisher_ips: []
remote_subscriber_ips: []
is_expose_to_remote_sub : False
is_remote_kill : False

print_status  : True
print_debug   : True

logging_spec:
  # Choose whether to periodically write data to files.
  stream_hdf5     : True # recommended over CSV since it creates a single file
  stream_csv      : False # will create a CSV per stream
  stream_video    : True
  stream_audio    : False
  stream_period_s : 10 # how often to save streamed data to disk
  
  # Choose whether to write all data at the end.
  #   Seems to be mutually exclusive with `stream_` options.
  dump_csv        : False
  dump_hdf5       : False
  dump_video      : False
  dump_audio      : False
  
  # Additional configuration.
  #   Choose whether to save media separately or as part of HDF5/CSV files.
  videos_in_hdf5  : False
  videos_in_csv   : False
  video_codec     : 'h264_nvenc'
  
  audio_format    : "wav" # currently only supports WAV
  audio_in_hdf5   : False
  audio_in_csv    : False


producer_specs:
  # Vicon capture system.
  - class: "CameraStreamer"
    camera_mapping: # map camera names (usable as device names in the HDF5 file) to capture device indexes
      basler_north : "40478064"
      basler_east  : "40549960"
      basler_south : "40549975"
      # basler_west  : "40549976"
    fps: 30
    resolution:
      - 1440
      - 2560
    camera_config_filepath: "resources/AidFOG/pylon_30fps_2K.pfs"
   

consumer_specs: []
#   - class: "DataLogger"
#     logging_spec:
#       # Choose whether to periodically write data to files.
#       stream_hdf5     : True # recommended over CSV since it creates a single file
#       stream_csv      : False # will create a CSV per stream
#       stream_video    : True
#       stream_audio    : False
#       stream_period_s : 10 # how often to save streamed data to disk
#       clear_logged_data_from_memory: True # NOTE: IGNORED if dumping is also enabled below
      
#       # Choose whether to write all data at the end.
#       #   Seems to be mutually exclusive with `stream_` options.
#       dump_csv        : False
#       dump_hdf5       : False
#       dump_video      : False
#       dump_audio      : False
      
#       # Additional configuration.
#       #   Choose whether to save media separately or as part of HDF5/CSV files.
#       videos_format   : "avi" # mp4 occasionally gets openCV errors about a tag not being supported?
#       videos_in_hdf5  : False
#       videos_in_csv   : False
#       audio_format    : "wav" # currently only supports WAV
#       audio_in_hdf5   : False
#       audio_in_csv    : False
#     stream_specs:
#       - class: "CameraStreamer"
#         camera_mapping: # map camera names (usable as device names in the HDF5 file) to capture device indexes
#           # basler_north : "40478064"
#           # basler_east  : "40549960"
#           # basler_south : "40549975"
#           basler_west  : "40549976"
#         fps: 20
#         resolution:
#           - 1944
#           - 2592
#         color_format: "COLOR_BAYER_RG2RGB" # Must be a valid OpenCV color format
#         camera_config_filepath: "resources/AidWear/pylon_20fps_maxres.pfs"

pipeline_specs: []
