name: aidwear
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26.*
  - beautifulsoup4
  - h5py
  - msgpack-python
  - openpyxl
  - pandas
  - pynput
  - pyaudio
  - pyopengl
  - pyqt
  - pyqtgraph
  - pyserial
  - pyusb
  - pyzmq
  - pyperclip
  - scipy
